# ===============================
# EMBEDDED WEB SERVER
# Custom names:
# lang-trainer - основа web-адреса приложения
# ===============================
server:
  port: 8090
  servlet:
    context-path: /lang-trainer
# ===============================
# Relational Database - Postgres
# Custom names:
# DB_URL - путь к базе данных
# PG_USER - пользователь базы данных
# PG_PASSWORD - пароль базы данных
# local.env - имя файла с "секретами"
# ===============================
spring:
  config:
    import: optional:file:local.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
# ===============================
# Custom Static Data
# ===============================
custom:
  init-data:
    roles: ROLE_ADMIN, ROLE_CUSTOMER
    levels: beginner, elementary, intermediate, upper-intermediate, advanced, proficiency